<?php

namespace Container3cgTqMN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCityListSenderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CityListSender' shared autowired service.
     *
     * @return \App\Service\CityListSender
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/CityListSender.php';

        return $container->privates['App\\Service\\CityListSender'] = new \App\Service\CityListSender();
    }
}
