<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBpgtGfi\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBpgtGfi/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerBpgtGfi.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerBpgtGfi\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerBpgtGfi\App_KernelTestDebugContainer([
    'container.build_hash' => 'BpgtGfi',
    'container.build_id' => 'f2a788a5',
    'container.build_time' => 1596112054,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBpgtGfi');
